# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'Ellmoe' do
  pod 'Crashlytics', '~> 3.13.2'

  pod 'GoogleMaps'

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  # pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

# target 'Ellmoe-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for Ellmoe-tvOS
#
#   target 'Ellmoe-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
